services:

  evo-crm:
    image: node:22-alpine
    container_name: evo-crm

    working_dir: /app

    volumes:
      - ./:/app

    command: sh -c "npm install && npm run dev"

    ports:
      - "3001:3000"

    environment:
      NODE_ENV: development

      DATABASE_URL: mysql://crm_user:HorsemenCRM@2026!@evo-mysql:3306/evo_crm

      NEXTAUTH_URL: http://localhost:3001
      NEXTAUTH_SECRET: 3YvLqgP7nXc9KzR2fQ8uWm4A!sJ6eB#Tt9DvH@2LpX5NcR8

    restart: unless-stopped

    networks:
      - evo-network

networks:
  evo-network:
    external: true